language: python
python:
  - "2.7"

# No need for this, only deploy
install:
  - true

# No need for this, only deploy
script:
  - true

before_deploy:
  - pwd
  - ./gen-tar.sh

deploy:
  provider: releases
  api_key:
    secure: IU2mY+LOiy97ZMhtVO+wX/b73YsuCvk7KCbToHPrWPYvnke7ATjVNx5sdDQMolduK5lMGFLwLTnDJYtDkiwP9qIg1cfQUQRGu7LBtJy4kjyQlRZZfOT8+iQOPwkSUpqvq5Vus7exgERt1MOCWtbyqF34g2BqnypCmcd2FjRBZFsb2rDFVA7QYbaZqBmmDEWk3UBH3wxOwnjwvQ/0dzT+QFyg3oVYwXgwiF1o8g+atQ0dO6hVukB0EH/sGSTLLfsH6uviem2IePNWlBr6UY1MmDTnx7V9MtJ5ByoT8QYNithK+My1rYOYaHc159MIv2LiGez4S5BnF2glFqmx6dixCjoYQ8bmmmfKjyZQRtSuNlPQrIIRA79Udj5v+rnf3JT0b0+bkSs98ORJ7dOdXIDTAGdJ8MbeP1H+VR5ngclsrE7FOn4LsivrozH5clCtA7KdB+aWNXD8KI9pPLmczqt95DcBSrRHiuBR7wz+jzIO2Q00Uwf4wUv/VbajChYIEGRkisHkW2CAsf7Yn4NhY23173M6GY0w90eLgVNPLfjL2+4NkoLh8/rbmigRHWbHMyCJP2rUUcnwOFKbPSta9X+/mOP53NLUXMtaQJug1MNHwI3iMWIRUyJeshkGN7xwUaR7CgytDtHzOFMQawQiGBE3JXBeg3a+YCb7ozqQZw1LXSc=
  file: weewx-zabbix.tgz
  on:
    repo: RandomReaper/weewx-zabbix
    branch: test-travis
