notifications:
  email:
    on_success: change
    on_failure: always
language: python
python:
- '2.7'
install:
- true
script:
- true
before_deploy:
- pwd
- "./gen-tar.sh"
deploy:
  provider: releases
  api_key:
    secure: n8oD79q1hxkHYUS1nfd/CnH+wqI1F6XOzVvU/eQnVr1rxnvdSD+n/NG83mm8c6UPiywhPGrz2DEdQbpDj8Prys7zWyD3eHKQU+Kus7l9pimnwOimpeEGzSdYqGg+RGnjCHEubFtgI7MRX9Lr65JFrSKw2/gAFvoPR6MPHyJqvfWmKwZMi5seRQlwFNAKeX6wS9ExUuqWyf0Zt55poTTXAnpIYvgQkYroGZce5cQpCiRVwyEaBblPlUfaQH9ploSyvb0SfldkdZt0xIdy2xukDACm4Ku1172qBe5YKf2o3zSeeeH1bMlfkxWUPaWZhB+AoDmwWU+yN9IXZJ9c/jdaOCi7HMst1J8MyfFWAQXrmJJ7Ypu9/qc8RoZuADGZ0v17OL3VltuHtvcQiCu1F8dVacoQjEi3MFMYPmOn1pICQVIQs7nQx72QcYdJv2vIp5qhYzUrUwK2t7s0VL/0hYOI2L8nS7t9r/j5xfzTXcQB4zTnnBS4OLqCtpclB9oqEYXa7clN6N4iGLC9zPX7vtEHcPoO4tXSmeyt9spdFtPwkPzdC1QKZ9AgzA0w2+IAwBrTR3Nemq2X63AWs9UzhPr9N8eYQsaO/5Zj5ZmSKFJy69QCIRvcbXQQq7PdLV97ykMf8Z3oX7JUQvTuphE/zEiDtWrLXMbtk8EfwhwGGGIDgg4=
  skip_cleanup: true
  file: weewx-zabbix.tgz
  on:
    branch: master
    repo: RandomReaper/weewx-zabbix


